### PR TITLE
Revamp 2

### PR DESCRIPTION
**Pull request by resyfer**
Fixed some dead links in there, plus some I had left as TODO link to content, but forgotten to link after writing the content.

### CODE REVIEW

**Comment by jesperpedersen** [comment]
Conflicts, resolve, please

**Comment by resyfer** [comment]
@jesperpedersen PTAL...was having some issues with git (probably can't squash when merge commit? or maybe idk how to do it).

**Comment by resyfer** [comment]
Hmmm, one more link dead. I did fix this, but probably merge conflict was improperly solved.

**Comment by jesperpedersen** [comment]
Merged.

Site is still broken.

**Pull request merged**
